### ISSUE TITLE
this.chart.render is not a function

### ISSUE THREAD

**Issue by ZiFFeL1992** [apexcharts/vue-apexcharts#184]
After upgrading from 1.3.6 to 1.5.1 seems we have this error, after further research it seems to be related with our bundler, [parcel](https://github.com/parcel-bundler/parcel/).

Viewing changes between those tags I notice that imported apex changed, I fixed by changing:

```diff
diff --git a/dist/vue-apexcharts.js b/dist/vue-apexcharts.js
index ff8a17c..9c5a854 100644
--- a/dist/vue-apexcharts.js
+++ b/dist/vue-apexcharts.js
@@ -1,11 +1,10 @@
 (function (global, factory) {
-  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('apexcharts/dist/apexcharts.common'), require('apexcharts')) :
-  typeof define === 'function' && define.amd ? define(['apexcharts/dist/apexcharts.common', 'apexcharts'], factory) :
-  (global.VueApexCharts = factory(global.ApexCharts,global.ApexCharts));
-}(this, (function (ApexCharts,ApexCharts$1) { 'use strict';
+  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('apexcharts')) :
+  typeof define === 'function' && define.amd ? define(['apexcharts'], factory) :
+  (global.VueApexCharts = factory(global.ApexCharts));
+}(this, (function (ApexCharts) { 'use strict';
```

```diff
diff --git a/src/ApexCharts.component.js b/src/ApexCharts.component.js
index f232109..ae3fe35 100644
--- a/src/ApexCharts.component.js
+++ b/src/ApexCharts.component.js
@@ -1,4 +1,4 @@
-import ApexCharts from 'apexcharts/dist/apexcharts.common'
+import ApexCharts from 'apexcharts'
```

`factory(require('apexcharts'))` -> `factory(require('apexcharts/dist/apexcharts.common'))`

Is there any way I can fix this issue on my side?

**Comment by fizerkhan** [comment]
+1

**Comment by ZiFFeL1992** [comment]
There's a workaround that comes to my mind, 

```json
{
   (...)
    "alias": {
        "apexcharts": "apexcharts/dist/apexcharts.common"
    }
}
```

Adding alias field to `package.json` does the trick, you can find more info: https://parceljs.org/module_resolution.html#aliases
